version: '3'

volumes:
  mysql_data:
    driver: local

services:
  mysql-server:
    image: jizuzquiza/mysql:8.0.16
    environment:
      MYSQL_ROOT_PASSWORD: password@1
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
    - 3306:3306
